### ISSUE TITLE
Expires prop has incorrect types

### ISSUE THREAD

**Issue by KubaZachacz** [andreizanik/cookies-next#11]
docs says:
```
expires
Date object or number days count
```
but it seems like number is not a correct type 
```
TypeError: option expires is invalid
```
it looks like it goes down to 'cookie' library which has type:
```
    expires?: Date | undefined;
```

**Comment by andreizanik** [comment]
Thanks, you are right! 
I corrected the documentation in release v2.0.5

You need to use `maxAge` if you want to specify a number (in second)
