### ISSUE TITLE
can not run on ios10

### ISSUE THREAD

**Issue by xuqianjin** [andreizanik/cookies-next#2]
error message
```
Unexpected token '{'. Expected '(' to start a 'catch' target
```
maybe in the 
```
const stringify = (value = '') => {
	try {
		const result = JSON.stringify(value);
		return (/^[\{\[]/.test(result)) ? result : value;
	} catch {
		return value;
	}
};
```
the catch missed the variable

**Comment by andreizanik** [comment]
Can you test this?
`const stringify = (value = '') => {
	try {
		const result = JSON.stringify(value);
		return (/^[\{\[]/.test(result)) ? result : value;
	} catch (e) {
		return value;
	}
};`

This is in the **fix-catch** branch.

**Comment by andreizanik** [comment]
fix https://github.com/andreizanik/cookies-next/pull/3
