### ISSUE TITLE
Trying to set a simply cookie

### ISSUE THREAD

**Issue by santyas** [andreizanik/cookies-next#23]
Hello! I'm getting this alert:

TS2345: Argument of type ' "test" ' is not assignable to parameter of type 'Pick  | { res: NextApiResponse ; } | { res: express.Response; } | null | undefined'.

When I try to set:
setCookie( 'test', 'value', {} )
Inside getServerSideProps or not...

Im using Next.js 12.2 and Typescript :(
Thanks,
S

**Comment by andreizanik** [comment]
Hello! 
What package version are you using?

**Comment by mgonzalez-preferredhotels** [comment]
Hi @andreizanik Same error here i just update to from next 12.2.0 from next 10 and the setCookie seems to not be present in the type annotations:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/108835644/179312394-06d13256-e296-4848-b040-0ab50f915e61.png">

Ignoring TS for that import seems to solve it :
`// @ts-ignore`


```
"next": "12.2.2",
"react": "18.2.0",
"react-dom": "18.2.0",
"cookies-next": "2.1.1",
```

**Comment by andreizanik** [comment]
Hi @mgonzalez-preferredhotels 
index.d.ts contains both functions 

```
export declare const setCookie: (key: string, data: any, options?: OptionsType) => void;
export declare const setCookies: (key: string, data: any, options?: OptionsType) => void;
```

I just checked this by installing the package from npm 


Hi, @santyas
I checked your problem and I don't have it

```
export async function getServerSideProps({ req, res }: GetServerSidePropsContext) {
  setCookie('test', 'value', { req, res });

  return { props: {} };
}
```
It's ok for me
I need more information, has anyone experienced the same problem?

**Comment by andreizanik** [comment]
@santyas did you solve your problem?
