### ISSUE TITLE
Setting a Cookie and getting it back doesnt seem to work

### ISSUE THREAD

**Issue by LuMiSxh** [andreizanik/cookies-next#24]
Hello, I currently try to store data with cookies. I've written my own functions to make it return default values, if "undefined" or "null" is given. This code looks as follows:
```ts
import { getCookie, hasCookie, setCookie } from 'cookies-next';

export function getCookieResult<T = any>(defaultValue: T, name: string): T {
  if (!hasCookie(name)) {
    setCookieResult<T>(defaultValue, name);
  }
  const result = getCookie(name)?.toString();
  return result ? JSON.parse(result) : defaultValue;
}

export function setCookieResult<T = any>(data: T, name: string) {
  setCookie(name, JSON.stringify(data), { maxAge: 60 * 60 * 24 * 100 });
}
```
The problem im facing is, that if I try to get the cookies, it sometimes won't pass the hasCookie check and return undefined when the getCookie gets called, even tho the cookie is still present.  Am i doing anything wrong?

An example on how the method works clientside: 
```ts
const settings = getCookieResult<userSettings>(
    { isDark: true, isManual: false },
    'UserSettings'
  );
```

**Comment by andreizanik** [comment]
Hi!
May be do you set httpOnly  cookie on server? 
https://github.com/andreizanik/cookies-next#httponly

Or set cookes with path in options? 
https://github.com/andreizanik/cookies-next#path


Your code is correct and always works for me

**Comment by LuMiSxh** [comment]
Hey, thanks for the relatively quick answer. I found a bug in my program that let to it being called multiple times and that was the problem. But thanks for taking the time of testing it!
