### ISSUE TITLE
How to use cookies-next with getServerSideProps(context)

### ISSUE THREAD

**Issue by GravyPouch** [andreizanik/cookies-next#25]
I'm not sure if this is a noob question, but how would one use this package while also using [getServerSideProps(context)](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#context-parameter).

` setCookie("zipcode", zipcode, {context.req, context.res});`

I'm trying to set a cookie using the above code, but keep receiving a syntax error.

> Error:
  x Unexpected token `.`. Expected ... , *,  (, [, :, , ?, = or an identifier
    ,----
 51 | setCookie("zipcode", zipcode, {context.req, context.res});
    :                                       ^
    `----
Caused by:
    0: failed to process input file
    1: Syntax Error

Any help would be greatly appreciated, thank you.

**Comment by nonwiz** [comment]
> I'm not sure if this is a noob question, but how would one use this package while also using [getServerSideProps(context)](https://nextjs.org/docs/api-reference/data-fetching/get-server-side-props#context-parameter).
> 
> ` setCookie("zipcode", zipcode, {context.req, context.res});`
> 
> I'm trying to set a cookie using the above code, but keep receiving a syntax error.
> 
> > Error:
> > x Unexpected token `.`. Expected ... , *,  (, [, :, , ?, = or an identifier
> > ,----
> > 51 | setCookie("zipcode", zipcode, {context.req, context.res});
> > :                                       ^
> > `----
> > Caused by:
> > 0: failed to process input file
> > 1: Syntax Error
> 
> Any help would be greatly appreciated, thank you.

You got invalid syntax on your third parameters.

Option 1:
`setCookie("zipcode", zipcode, {req: context.req, res: context.res})`

Option 2:
`
const { req, res} = context;
setCookie("zipcode", zipcode, {req, res})
`

**Comment by GravyPouch** [comment]
Thank you so much, I was being dumb.
