### ISSUE TITLE
Typescript Error : Object literal may only specify known properties, and 'sameSite' does not exist in type 'OptionsType'

### ISSUE THREAD

**Issue by a7medmo7med9** [andreizanik/cookies-next#26]
how can i add this options

![1](https://user-images.githubusercontent.com/34967435/188229077-91f0d669-5df1-4ab5-aa62-ac69a65f601f.PNG)

![2](https://user-images.githubusercontent.com/34967435/188229089-439079df-4130-4ac5-bb2a-d22131fc44f4.PNG)

![3](https://user-images.githubusercontent.com/34967435/188229403-257a77d9-9205-41d7-ad5f-59a9014c848a.PNG)

iam using 
` // @ts-ignore
`

**Comment by andreizanik** [comment]
it works for me
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/3517891/189348981-ed373f05-db38-4bf7-a716-56425c2cf8d6.png">
<img width="655" alt="image" src="https://user-images.githubusercontent.com/3517891/189349041-80874a0d-3a16-438b-b2f5-eb43ef77c17a.png">

this option is contained in CookieSerializeOptions.

Can you show your package.json? May be a problem with the version of the package "cookie" or "@types/cookie"

**Comment by davesag** [comment]
I was getting this issue too `cookies-next` version

<img width="1027" alt="Screenshot 2022-11-18 at 11 22 03 am" src="https://user-images.githubusercontent.com/387098/202588314-66c548b8-5c6c-4de9-a250-aaecac39f001.png">

Fixed by `npm I -D @type/cookie`
