### ISSUE TITLE
`cookie-next` is not installing via `yarn`

### ISSUE THREAD

**Issue by MahendraBishnoi29** [andreizanik/cookies-next#42]
`error An unexpected error occurred: "https://registry.yarnpkg.com/cookie-next: Not found".    
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\Priyadarsh S S\\OneDrive\\Desktop\\questing-platform\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**Comment by MahendraBishnoi29** [comment]
@andreizanik

**Comment by andreizanik** [comment]
Hello. 
Please, check this issue https://github.com/yarnpkg/yarn/issues/5865
Maybe there is a solution for your problem

**Comment by andreizanik** [comment]
@MahendraBishnoi29  
Did you solve the problem?

**Comment by MahendraBishnoi29** [comment]
> @MahendraBishnoi29 Did you solve the problem?

yes I did🚀
