### ISSUE TITLE
Next13 getCookie

### ISSUE THREAD

**Issue by devDalys** [andreizanik/cookies-next#57]
Hi
Help please, I'm trying to use your library with Next13 and the App folder and I getCookie always returns undefined on the server side
While the standard cookies().get() method from next/headers gives a valid response

**Comment by greg2012201** [comment]
Hello,

In the current version of cookies-next, it is not possible to use getCookie in Server Components or Server Actions. However, I have submitted PR #55, where I implemented a solution that provides the possibility to seamlessly use cookies-next in Next.js 13+. I'm waiting for @andreizanik to merge this PR, so stay in touch.

**Comment by samuhmatos** [comment]
I am having the same problem.... Next.js already has arrived and still no update to supports v13

**Comment by andreizanik** [comment]
https://github.com/andreizanik/cookies-next/releases/tag/v4.1.0
