### ISSUE TITLE
Update cookie package

### ISSUE THREAD

**Issue by tkrotoff** [andreizanik/cookies-next#60]
The [cookie package](https://github.com/jshttp/cookie/releases) used is version 0.4.0 (or 4.0.2 thx to ^) from 2019: https://github.com/andreizanik/cookies-next/blob/20d01df448a8a97fb30ff9068e6dff56dd0fc1c7/package.json#L40

**Comment by Victor1890** [comment]
@tkrotoff PR done in #62

**Comment by andreizanik** [comment]
release https://github.com/andreizanik/cookies-next/releases/tag/v4.1.1

Thanks @Victor1890
