### ISSUE TITLE
Setting cookie value as "true" (boolean) and then getting it throws an error

### ISSUE THREAD

**Issue by blopa** [andreizanik/cookies-next#66]
Hi. If I set a cookie as `true` (boolean) and try to get it, it will go to the `decode` function as a boolean (not a string, I don't know why), then [this condition](https://github.com/andreizanik/cookies-next/blob/26d06af43298ace97037a7b6a5a0691565ac3f8d/src/index.ts#L56) will fail (because `!true` is `false`), then on the next line will try to use String.replace, which doesn't exist on a boolean.

I'm using `cookies-next` version `4.1.1` and `next` version `14.1.4`.

This is the code that I've used and it fails:

```javascript
    setCookie('MY_TEST_COOKIE', true, { req, res });
    console.log('MY TEST COOKIE HERE', getCookie('MY_TEST_COOKIE', { req, res }));
```

![image](https://github.com/andreizanik/cookies-next/assets/3838114/f91b1baa-67b7-4ad6-bf9e-304bd3d16b50)

**Comment by andreizanik** [comment]
It is fixed in the version [v4.2.0](https://github.com/andreizanik/cookies-next/releases/tag/v4.2.0)
