### ISSUE TITLE
Next.js 15 support

### ISSUE THREAD

**Issue by joaopcm** [andreizanik/cookies-next#85]
Internally, the `cookies` property should be called asynchronously when using Next.js 15+, or else the Next.js engine will throw an error due to the misuse of the [Cookies API](https://nextjs.org/docs/app/api-reference/functions/cookies).

**Comment by joaopcm** [comment]
I'm working on it, btw

**Comment by joaopcm** [comment]
#86

**Comment by andreizanik** [comment]
done https://github.com/andreizanik/cookies-next/releases/tag/v5.0.0
