### ISSUE TITLE
Error when running new version 5.0.0.

### ISSUE THREAD

**Issue by thuyng-ing** [andreizanik/cookies-next#89]
When upgrading to this version, I encountered this error when running vitest 
`Failed to resolve entry for package "cookies-next". The package may have incorrect main/module/exports specified in its package.json.`
Downgrade back to 4.3.0 fixed the issue

Steps to Reproduce:
Install version 5.0.0 and run vitest

**Comment by barrenechea** [comment]
It seems the `lib` folder was not distributed for 5.0.0, missed a build maybe? 😜 

https://www.npmjs.com/package/cookies-next/v/5.0.0?activeTab=code

**Comment by andreizanik** [comment]
Let me check what happened

**Comment by andreizanik** [comment]
Yes, there is no folder "lib" but I can't figure out why. 

I published a new version where it is definitely there. But after publishing it is still not there

I need more time

**Comment by andreizanik** [comment]
Please try version [5.0.2](https://www.npmjs.com/package/cookies-next/v/5.0.2)

**Comment by barrenechea** [comment]
Everything is working on my side after using `cookies-next/client`! Thank you very much 🚀
